# Generated by Django 3.0.5 on 2020-04-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bname', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'allaboutfeet_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cname', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'allaboutfeet_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('color', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'allaboutfeet_colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'allaboutfeet_productbrand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('dprice', models.IntegerField(blank=True, null=True)),
                ('desciption', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'allaboutfeet_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('size', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'allaboutfeet_sizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('sname', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'allaboutfeet_style',
                'managed': False,
            },
        ),
    ]
