# Generated by Django 3.0.5 on 2020-04-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allaboutfeet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productsizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'allaboutfeet_productsizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productsubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'allaboutfeet_productsubs',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Productbrand',
        ),
    ]
