# Generated by Django 3.0.5 on 2020-05-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allaboutfeet', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('dprice', models.IntegerField(blank=True, null=True)),
                ('desciption', models.CharField(blank=True, max_length=100, null=True)),
                ('imagename', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'productdetails',
                'managed': False,
            },
        ),
    ]
